### ISSUE TITLE
Read `mod.conf` to determine the title

### ISSUE THREAD

**Issue by appgurueu** [mineclone2-mods/modname_tooltip#3]
There's no need to duplicate this in an API

**Comment by AFCMS** [comment]
I have considered this option, but some mods are actually modpacks, even if they provided an united experience.
The API is really needed for this specific case.

I didn't know that `minetest.get_modnames()` existed to check for mod titles at startup, so I will now implement something like this for the tooltip:
API > mod title > modname

**Comment by AFCMS** [comment]
fixed by 910987f4a9c28d805640d7d519a2b15c307b4de4
